language: python
addons:
  sonarcloud:
    organization: "mkody-github"
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install flake8
script:
  - flake8 .
jobs:
  include:
    - stage: "sonar"
      script: sonar-scanner
      python: "3.6"
